### PR TITLE
Added mACM conformance resources.

### PR DESCRIPTION
**Pull request by lukeaduncan**
Added in mACM conformance resources.  I'm not sure if the codesystem and valueset values are correct.  I don't know if the URL needs to be a urn:oid: or the URL as I put it.

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
@lduncan-intrah did you run the FHIR validator on these? Did they pass validation?

**Comment by JohnMoehrke** [comment]
The CodeSystems should not put the OID into the URL. The OID is properly in the codeSystem as a .identifier. 
The struggle that is not clear is that you are publishing a vocabulary that is owned by IEEE. Would we really just create a ValueSet with these codes explicitly in that ValueSet? I will do some investigation.

**Comment by JohnMoehrke** [comment]
Why did you create an OID for mACM use? Is there somewhere in the profile where an OID must be used?

**Comment by lukeaduncan** [comment]
> @lduncan-intrah did you run the FHIR validator on these? Did they pass validation?

Sorry, I was rushing before heading to the airport.  I'm running the validator now, but I just updated it and it's downloading a lot.  I'll update here when it finishes, but that may not be until after I arrive home sometime tomorrow.

**Comment by lukeaduncan** [comment]
> The CodeSystems should not put the OID into the URL. The OID is properly in the codeSystem as a .identifier.
> The struggle that is not clear is that you are publishing a vocabulary that is owned by IEEE. Would we really just create a ValueSet with these codes explicitly in that ValueSet? I will do some investigation.

The ValueSets I created may be enough then.  I wasn't sure where those CodeSystems came from.  Although the 5.1 is probably unique.  It looked like it was created for mACM.  I didn't write this one, so I'm not sure how they were created.  I pulled the data from tables in the profile.

**Comment by lukeaduncan** [comment]
> > @lduncan-intrah did you run the FHIR validator on these? Did they pass validation?
> 
> Sorry, I was rushing before heading to the airport. I'm running the validator now, but I just updated it and it's downloading a lot. I'll update here when it finishes, but that may not be until after I arrive home sometime tomorrow.

The StructureDefinitions were good.  There were some issues with some of the others, but I'll follow-up with you when I get home.

**Comment by JohnMoehrke** [comment]
so if we don't need OIDs. then lets not use OIDs in mACM, just using mACM centeric ValueSet names.

**Comment by lukeaduncan** [comment]
I have fixed some validation errors in the codesystems and valuesets.  The issue was the name which had periods in it to match the OID.  I replaced those with underscores.  I don't know if that's a good choice for name or not.

The only remaining validation errors are in the capabilitystatements.  It complains about the definition URL in the search parameters.  I got this from another example, so I don't know if it's an issue with the validator or with what I did.  I can certainly remove them since it's optional.

The only issue with the OIDs is that they are in the profile right now.  I suppose that might be something we can change if we take it out of the TI process quickly and make that change.  Right now it refers to those OIDs.  I don't know if they're documented elsewhere, but I seem to remember they're in a list of OIDs we use somewhere.

Table 3.84.4.1.2.1-1 refers to one under the category field.  Table 3.84.4.1.2.1.1-1 and 3.84.4.1.3.1-1: do for reasonCode.  Tables 3.84.5.1-1, 3.84.5.1-2, and 3.84.5.1-3 have them defined.

**Comment by JohnMoehrke** [comment]
Those tables are specific to mACM. I don't think we should have defined
them using OIDS. The use of OIDS is certainly a ACM thing, but when we
transition to mACM we should have created url friendly ValueSets. By
leaving the OID in as an .identitier, you will be supporting the current
supplement text.
* So I recommend you come up with more human friendly URL, leaving in the
.identifier which is the OID.
* Then use that URL in your other structure definitions that call upon the
valuesets

John Moehrke 🔥 Architect: Healthcare Informatics Standards -
Interoperability, Privacy, and Security
CyberPrivacy – Enabling authorized communications while respecting Privacy
IHE Co-Chair IT Infrastructure Planning
HL7 Co-Chair Security WG, FHIR FMG, FHIR facilitator, and FHIR Foundation
founding member
HITRUST Certified CSF Practitioner
Employee of ByLight Professional IT Services -- Contractor to VHA
MyHealtheVet
JohnMoehrke@gmail.com  |  M +1 920-564-2067  |  John.Moehrke@bylight.com
https://www.linkedin.com/in/johnmoehrke   |
https://healthcaresecprivacy.blogspot.com
Courtney's third law: There are no technical solutions to management
problems, but there are management solutions to technical problems.

**Comment by JohnMoehrke** [comment]
On the capability statement... take a look at MHD, I had to fix a bunch of
things, I did update the IHE wiki guidance, but it might be quicker to
compare with MHD

John Moehrke 🔥 Architect: Healthcare Informatics Standards -
Interoperability, Privacy, and Security
CyberPrivacy – Enabling authorized communications while respecting Privacy
IHE Co-Chair IT Infrastructure Planning
HL7 Co-Chair Security WG, FHIR FMG, FHIR facilitator, and FHIR Foundation
founding member
HITRUST Certified CSF Practitioner
Employee of ByLight Professional IT Services -- Contractor to VHA
MyHealtheVet
JohnMoehrke@gmail.com  |  M +1 920-564-2067  |  John.Moehrke@bylight.com
https://www.linkedin.com/in/johnmoehrke   |
https://healthcaresecprivacy.blogspot.com
Courtney's third law: There are no technical solutions to management
problems, but there are management solutions to technical problems.

**Comment by lukeaduncan** [comment]
I updated the valuesets and codesystems.  I also modified the structuredefinitions to take out the slices for valueset binding until further decisions are made on this.

The capability statements are based on the MHD ones.  The only validation errors I get on are those and are all similar to this:
  Error @ CapabilityStatement.rest[0].resource[1].searchParam[16].definition (line 266, col84) : URL value 'http://hl7.org/fhir/SearchParameter/Communication-subject' does not resolve

**Comment by JohnMoehrke** [comment]
drat.. the following is what I thought was the solution... but
Communication resource seems to be an oddball. That said, try this anyway...

Some search parameters are not specific to the Resource type, but are
generic. Such as "clinical-patient". You can only know this by going to the
search parameter registry.

http://hl7.org/fhir/searchparameter-registry.html

See DocumentReference as the case I ran into... BUT Communication and
CommunicationRequest don't seem to use these general search parameters.

BUT, Try it anyway. change to 'clinical-subject'...


John Moehrke 🔥 Architect: Healthcare Informatics Standards -
Interoperability, Privacy, and Security
CyberPrivacy – Enabling authorized communications while respecting Privacy
IHE Co-Chair IT Infrastructure Planning
HL7 Co-Chair Security WG, FHIR FMG, FHIR facilitator, and FHIR Foundation
founding member
HITRUST Certified CSF Practitioner
Employee of ByLight Professional IT Services -- Contractor to VHA
MyHealtheVet
JohnMoehrke@gmail.com  |  M +1 920-564-2067  |  John.Moehrke@bylight.com
https://www.linkedin.com/in/johnmoehrke   |
https://healthcaresecprivacy.blogspot.com
Courtney's third law: There are no technical solutions to management
problems, but there are management solutions to technical problems.

**Comment by lukeaduncan** [comment]
clinical-subject also gave an error.  That was just an example.  I get an error on every single searchparameter definition and they match the id given on the searchparameter registry.  I get the same thing on MHD capability statements when I validate those.

**Pull request merged**
