### PR TITLE
updated to NPFS

### PR DESCRIPTION
**Pull request by gregoriocanal**

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
Did you confirm that these updates do validate with the FHIR validator?

**Comment by gregoriocanal** [comment]
they passed validation 4 months ago,
i just replaced NPFSm with NPFS

**Comment by JohnMoehrke** [comment]
thanks

**Comment by JohnMoehrke** [comment]
did you mean to close the pull request?

**Comment by gregoriocanal** [comment]
in order to be sure i've runned the validator and they are valid resources. So we can close the pull request

**Comment by gregoriocanal** [comment]
yes i colsed this pull request because i updeted one of the resources that i have deleted.

**Pull request closed without merging**
