### PR TITLE
Update StructureDefintion for IHE PMIR to 4.0.1 and CP-ITI-1197

### PR DESCRIPTION
**Pull request by oliveregger**
This PR provides the following changes:
- update StructureDefintions to 4.0.1
- removed snaphshots to rely on snaphshot generation by differential
- changed id/canonical url's _ char with '.' (_ ist not allowed in id)

Incorporated [CP-ITI-1197](https://drive.google.com/drive/folders/1ufVTnHz2ZiWt9KH0o4ZSKDQxrBWnnDiU) which updates the  Message Semantics for ITI-93 Mobile Patient Identity Feed (BundleHistory instead of Patient resources).

Examples of the adapted StructureDefinitions are in this [ImplementationGuide](http://build.fhir.org/ig/ehealthsuisse/ch-epr-mhealth/branches/master/qa.html)

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
@lduncan-intrah please review this pull request and comment on your finding.

**Comment by JohnMoehrke** [comment]
@lduncan-intrah has indicated that he is still working on this, that there are some corrections he wants before this is merged.

**Comment by JohnMoehrke** [comment]
@oliveregger do you have examples that validate to this?

**Comment by oliveregger** [comment]
see http://build.fhir.org/ig/ehealthsuisse/ch-epr-mhealth/branches/master/Bundle-BundlePmirFeed.xml.html (the validation report is here: http://build.fhir.org/ig/ehealthsuisse/ch-epr-mhealth/qa.html ) and source of that for the ig is here: https://github.com/ehealthsuisse/ch-epr-mhealth/blob/master/input/examples/bundle/BundlePmirFeed.json

**Comment by lukeaduncan** [comment]
I made some minor tweaks.  But I'm not sure how to include them in this pull request.  I made a branch in this repo called oe_pmir_401 for review.  The main thing was some tweaks to the slicing definition and I split out the subscription so the main one doesn't restrict the status and added a profile for subscription request that does. @oliveregger can you look at that and see if it works for you?  [https://github.com/IHE/fhir/compare/oe_pmir_401](https://github.com/IHE/fhir/compare/oe_pmir_401)

**Comment by oliveregger** [comment]
@lduncan-intrah i updated the PR with your changes and rebased also the PR to master. The changes are working, thanks a lot! Can the PR be accepted this way?

**Comment by lukeaduncan** [comment]
Looks good to me.  Thanks!

**Comment by JohnMoehrke** [comment]
@lduncan-intrah are we good with merging this pull request? I see you made changes to master, so am not sure what the status should be for this pull request.

**Comment by lukeaduncan** [comment]
We can merge it.  I intended to make changes to a separate branch, so it was an accident if I changed master for these files.

**Pull request merged**
