### PR TITLE
Update of MHD conformance resources for FHIR R4

### PR DESCRIPTION
**Pull request by JohnMoehrke**
first draft for committee review

### CODE REVIEW

**Comment by JohnMoehrke** [comment]
Don't merge pull request until after committee review

**Comment by lynnfel** [comment]
In structuredefinition-IHE_MHD_Minimal_List.xml.... for element List.identifier, shouldn't min value be "2" instead of "1"?

**Comment by lynnfel** [comment]
In structuredefinition-IHE_MHD_Minimal_List.xml.... for element List.entry.item, I think it should be <min value="1">  ie min not max.

**Comment by lynnfel** [comment]
I think you are missing the file structuredefinition_IHE_Minimal_DocumentReference.xml

**Comment by lynnfel** [comment]
I compared the constraints in structuredefinition_IHE_Minimal_DocumentManifest.xml against my interpretation of the constraints in the profile, and I have no changes to suggest.

**Comment by lynnfel** [comment]
In structuredefinition-IHE_MHD_Comprehensive_List.xml, add a constraint for List.title with min=value"1" because Folder.title is not required for Minimal XDS Metadata, but it is required for an ITI-41 done by a regular Doc Source.

**Comment by lynnfel** [comment]
I compared the constraints in structuredefinition_IHE_Comprehensive_DocumentManifest.xml against my interpretation of the constraints in the profile, and I have no changes to suggest.

**Comment by lynnfel** [comment]
I think you are missing the file structuredefinition_IHE_Comprehensive_DocumentReference.xml

**Comment by JohnMoehrke** [comment]
> In structuredefinition-IHE_MHD_Minimal_List.xml.... for element List.identifier, shouldn't min value be "2" instead of "1"?

@lynnfel We can't set it to 2, as the server assigns the folder UUID. So I set it at min of 1 so that the Provide transaction is okay. The folder UUID might also not ever be added when not bound to XDS (non XDS-on-FHIR).

Lynn's response:  ok

**Comment by JohnMoehrke** [comment]
> In structuredefinition-IHE_MHD_Minimal_List.xml.... for element List.entry.item, I think it should be ie min not max.

@lynnfel no. the max value is just on the List.entry.item (which oddly can't repeat). We repeat at the List.entry (0..*) level. XDS does allow an empty folder, so I left this (0..*).

**Comment by JohnMoehrke** [comment]
> I think you are missing the file structuredefinition_IHE_Minimal_DocumentReference.xml

@lynnfel no, there is no generic minimal. There is only the minimal at Provide and a second at Query. Unless you see a reference that I missed?

**Comment by JohnMoehrke** [comment]
> In structuredefinition-IHE_MHD_Comprehensive_List.xml, add a constraint for List.title with min=value"1" because Folder.title is not required for Minimal XDS Metadata, but it is required for an ITI-41 done by a regular Doc Source.

@lynnfel okay, I will fix.

**Comment by JohnMoehrke** [comment]
> I think you are missing the file structuredefinition_IHE_Comprehensive_DocumentReference.xml

@lynnfel no, the comprehensive is different between Provide and Query. There is no generic comprehensive.

**Comment by JohnMoehrke** [comment]
branch has been updated with fix identified by Lynn

**Pull request merged**
